[package]
name = "spyro-rt-autosplitter"
version = "0.2.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
asr = { git = "https://github.com/LiveSplit/asr", features = [ "alloc", "derive" ] }
bytemuck = "1.x"

# Thanks to https://www.namtao.com/rust#strict-lints
[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
indexing_slicing = "deny"
unreachable = "deny"
unimplemented = "deny"
unchecked_time_subtraction = "deny"
todo = "deny"
string_slice = "deny"
panic_in_result_fn = "deny"
panic = "deny"
exit = "deny"
as_conversions = "deny"
# Necessary for `asr` crate
useless_let_if_seq = "allow"
