[package]
name = "spyro-rt-autosplitter"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = ["spyro_rt_utils"]

[dependencies]
spyro_rt_utils = { path = "spyro_rt_utils/" }
asr = { git = "https://github.com/LiveSplit/asr" }

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
strip = true
