[package]
name = "spyro_rt_utils"
version = "0.1.0"
edition = "2024"

[dependencies]
asr = { git = "https://github.com/LiveSplit/asr", features = [
    # Defining your own settings structs, converting endianness, and binding to .NET classes.
    "derive",
]}
# Bytemuck can be used to define structs that are being read from the game's process.
bytemuck = { version = "1" }
