name: Rust

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Install Rust
        uses: ./.github/actions/rust

      - name: Check Build
        run: cargo check
      
      - name: Check Formatting
        run: fmt --all -- --check
      
      - name: Run Clippy
        run: clippy -- -D warnings
