name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Install Rust 1.88.0
        uses: docker://rust:1.88.0

      - name: Add wasm32
        run: rustup target add wasm32-unknown-unknown

      - name: Check
        run: cargo check
